services:
  client:
    container_name: client
    build: ./client/.
    volumes:
      - ./client:/code
    depends_on:
      - cosmos

  cosmos:
    container_name: cosmos
    image: "mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 5G
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10
    ports:
      - 8081:8081
      - 10251:10251
      - 10252:10252
      - 10253:10253
      - 10254:10254
      - 10255:10255
    expose:
      - "8081"
      - "10250-10255"
    
